spring.application.name=security-app
server.port=5050

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/resources/templates,src/main/resources/static

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

spring.datasource.username=postgres
spring.datasource.password=Lydia@1957
spring.datasource.url=jdbc:postgresql://localhost:5432/securityappdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true